routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes([
	'register' => false,
	
]);

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/galleta',function(){
	return view('layouts.plantilla');
});


Route::resource('rol','RolController');
Route::resource('autor','AutorController');
Route::resource('editorial','EditorialController');
Route::resource('libro','LibroController');
Route::resource('/usuario','UsuarioController');
Route::post('/porcentajea','PorcentajeController@aumentar')->name('porcentajeall.aumentar');
Route::post('/porcentajed','PorcentajeController@disminuir')->name('porcentajeall.disminuir');
Route::resource('aumentopreciolibro','AumentoPrecioController')->except(['create','store','destroy','show']);
Route::resource('restapreciolibro','RestaPrecioController')->except(['create','store','destroy','show']);

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
     protected $fillable = [
        'name', 'email', 'password', 'role_id','dni','sexo','direccion','telefono','fecha_nacimiento','foto','estado'
    ];

    public function rol(){
        return $this->belongsTo('App\Rol');
    }


    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

resources/views/users/create.blade.php
@extends('layouts.plantilla')


@section('content')

     <div class="col-lg-12 ">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">Agregar Informacion del usuario</h3>
            </div>


            <!-- BASIC FORM ELEMENTS -->
            <!--===================================================-->
         <form action="{{ route('usuario.store') }}" onsubmit="return esfechavalida()" method="post" enctype="multipart/form-data" class="panel-body form-horizontal form-padding">
                  @csrf
                  <!--Static-->
                  @include('users.formUser',['mensaje'=> 'crear'])
                              
               </form>
            <!--===================================================-->
            <!-- END BASIC FORM ELEMENTS -->


        </div>
    </div>



@endsection

resources/views/users/edit.blade.php
@extends('layouts.plantilla')


@section('content')



@include("recursos.validacion")
		
	 <div class="col-lg-12 ">
              <div class="panel">
                  <div class="panel-heading">
                      <h3 class="panel-title">Editar Informacion del usuario</h3>
                  </div>
      
      
                  <!-- BASIC FORM ELEMENTS -->
                  <!--===================================================-->
              <form  action="{{ route('usuario.update', $actualizar->id) }}" onsubmit="return esfechavalida()" enctype="multipart/form-data" method="post" class="panel-body form-horizontal form-padding">
                @csrf
                @method('PUT')
      



               <div class="form-group">
                  <label class="col-md-3 control-label" for="demo-text-input">Rol</label>
                      <div class="col-md-9">
                          <select class="form-control" required="" name="rol_id">
                            @forelse($roles as $rol)
                            
                              <option value="{{ $rol->id }}" @if($rol->id == $actualizar->rol_id) selected="" @endif>{{ $rol->japo_nombre }}</option>
                            @empty
                            <span class="text-danger">No se encontraron roles</span>

                            @endforelse
                          </select>
                          @error('rol_id')
                          <small class="help-block text-danger">{{ $message }}</small>
                          @enderror
                      </div>
                 </div>     


             

                




             <div class="form-group">
                    <label class="col-md-3 control-label" enctype="multipart/form-data" for="demo-text-input">Nombres - Apellidos</label>
                        <div class="col-md-9">
                            <input type="text" name="name" required="" value="{{ $actualizar->name }}"   id="demo-text-input" class="form-control" placeholder="Ingrese nombre y apellidos">
                            @error('name')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                 </div>

                 <div class="form-group">
                        <label class="col-md-3 control-label" for="demo-text-input">Email</label>
                        <div class="col-md-9">
                            <input type="text" name="email" required="" value="{{ $actualizar->email }}"    id="demo-text-input" class="form-control" placeholder="Ingrese Email">
                            @error('email')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                </div>

                  <div class="form-group">
                    <label class="col-md-3 control-label" for="demo-text-input">Password</label>
                        <div class="col-md-9">
                            <input type="password" name="password" required="" value="{{ $actualizar->password }}"   id="demo-text-input" class="form-control" placeholder="Ingrese password">
                            @error('password')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                 </div>
    


           <div class="form-group">
                    <label class="col-md-3 control-label" for="demo-text-input">Cedula</label>
                        <div class="col-md-9">
                            <input type="text" name="dni" required="" required="" onBlur="validarDocumento()" onKeyPress="return soloNumeros(event)"  id="documento" value="{{ $actualizar->dni }}"    class="form-control" placeholder="Ingrese cedula">
                            @error('dni')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                 </div>

                 <div class="form-group">
                    <label class="col-md-3 control-label" for="demo-text-input">Direccion</label>
                        <div class="col-md-9">
                            <input type="text" name="direccion" required="" value="{{ $actualizar->direccion }}"   id="demo-text-input" class="form-control" placeholder="Ingrese direccion">
                            @error('direccion')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                 </div>

                 <div class="form-group">
                    <label class="col-md-3 control-label" for="demo-text-input">Telefono</label>
                        <div class="col-md-9">
                            <input type="text" name="telefono" required="" value="{{ $actualizar->telefono }}"  id="demo-text-input" onKeyPress="return soloNumeros(event)" class="form-control" placeholder="Ingrese telefono">
                            @error('telefono')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                 </div>

                   <div class="form-group">
                        <label class="col-md-3 control-label" for="demo-email-input">Sexo</label>
                        <div class="col-md-9">
                            <select name="sexo" class="form-control" required="">
                              <option>Seleccion tipo de sexo</option> 
                              <option value="H" @if($actualizar->sexo == 'H') selected=""  @endif) >Hombre</option>
                              <option value="M" @if($actualizar->sexo == 'M') selected=""  @endif) >Mujer</option>
                            </select>
                            @error('sexo')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                    </div>

                     <div class="form-group">
                        <label class="col-md-3 control-label" for="demo-text-input">Fecha Nacimiento</label>
                        <div class="col-md-9">
                            <input type="text" name="fecha_nacimiento" required="" value="{{ $actualizar->fecha_nacimiento }}"    id="demo-text-input" class="form-control">
                            @error('fecha_nacimiento')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label">Seleccione Foto</label>

                         <div class="col-md-9" >
                          <div class="row">
                            <div class="col-md-4" >
                                <span class="pull-left btn btn-primary btn-file ">
                                Cargar Foto... <input type="file" name="foto">
                                </span>
                            </div>
                            <div class="col-md-8">
                                 @if(isset($actualizar->foto))
      
                    <img style="position: relative; left: 10px;" src="{{ asset('storage').'/'.$actualizar->foto }}" width="100">
                    @endif
                  </div>
                </div>  
                       </div>
                       

                            
                        @error('foto')
                             <small class="help-block text-danger">{{ $message }}</small>
                          @enderror
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label" for="demo-email-input">Estado</label>
                        <div class="col-md-9" >
                            <select name="estado" class="form-control">
                              <option>Seleccion de estado</option>  
                              <option value="A" @if($actualizar->estado == 'A') selected=""  @endif) >Activo</option>
                              <option value="I" @if($actualizar->estado == 'I') selected=""  @endif) >Inactivo</option>
                            </select>
                            @error('estado')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                    </div>
                        
          
                        
          
                        
                         
           <div class="modal-footer">
                      <a href="{{ route('usuario.index') }}" class="btn btn-default" type="button">Close</a>
                      <input type="submit" class="btn btn-primary"  onclick="return confirm('Desea Actualizar?')" value="Actualizar Usuario" name="">
                    
                   </div>
                  </form>
                  <!--===================================================-->
                  <!-- END BASIC FORM ELEMENTS -->
      
      
              </div>
          </div>

@endsection

resources/views/users/formUser.blade.php
@include("recursos.validacion")

  					<div class="form-group">
		                <label class="col-md-3 control-label" for="demo-text-input">Rol</label>
		                    <div class="col-md-9">
		                        <select class="form-control" required name="rol_id">
		                        	@forelse($roles as $rol)
		                        		
		                        		<option value="{{ $rol->id }}">{{ $rol->japo_nombre }}</option>
		                        	@empty
		                        	<span class="text-danger">No se encontraron roles</span>

		                        	@endforelse
		                        </select>
		                        @error('rol_id')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		             </div>




  					 <div class="form-group">
		                <label class="col-md-3 control-label" for="demo-text-input">Nombres - Apellidos</label>
		                    <div class="col-md-9">
		                        <input type="text" required="" name="name"  value="{{ old('name') }}" id="demo-text-input" class="form-control" placeholder="Ingrese nombre y apellidos">
		                        @error('name')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		             </div>

		             <div class="form-group">
		                    <label class="col-md-3 control-label" for="demo-text-input">Email</label>
		                    <div class="col-md-9">
		                        <input type="text" required="" name="email" value="{{ old('email') }}"   id="demo-text-input" class="form-control" placeholder="Ingrese Email">
		                        @error('email')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		            </div>

		              <div class="form-group">
		                <label class="col-md-3 control-label" for="demo-text-input">Password</label>
		                    <div class="col-md-9">
		                        <input type="password" required="" name="password"  id="demo-text-input" class="form-control" placeholder="Ingrese password">
		                        @error('password')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		             </div>
		


					 <div class="form-group">
		                <label class="col-md-3 control-label" for="demo-text-input">Cedula</label>
		                    <div class="col-md-9">
		                        <input type="text" required="" name="dni" required=""  value="{{ old('dni') }}" id="documento" onBlur="validarDocumento()" onKeyPress="return soloNumeros(event)"  id="documento" class="form-control" placeholder="Ingrese cedula">
		                        @error('dni')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		             </div>

		             <div class="form-group">
		                <label class="col-md-3 control-label" for="demo-text-input">Direccion</label>
		                    <div class="col-md-9">
		                        <input type="text" required="" name="direccion" value="{{ old('direccion') }}"  id="demo-text-input" class="form-control" placeholder="Ingrese direccion">
		                        @error('direccion')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		             </div>

		             <div class="form-group">
		                <label class="col-md-3 control-label" for="demo-text-input">Telefono</label>
		                    <div class="col-md-9">
		                        <input type="text" required="" name="telefono" value="{{ old('telefono') }}"  id="demo-text-input" class="form-control" onKeyPress="return soloNumeros(event)" placeholder="Ingrese telefono">
		                        @error('telefono')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		             </div>

		               <div class="form-group">
		                    <label class="col-md-3 control-label" for="demo-email-input">Sexo</label>
		                    <div class="col-md-9">
		                        <select name="sexo" required="" class="form-control">
		                        	<option value="">Seleccion tipo de sexo</option>	
		                        	<option value="H">Hombre</option>
		                        	<option value="M">Mujer</option>
		                        </select>
		                        @error('sexo')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		                </div>

		                 <div class="form-group">
		                    <label class="col-md-3 control-label" for="demo-text-input">Fecha Nacimiento</label>
		                    <div class="col-md-9">
		                        <input type="text" required="" name="fecha_nacimiento" value="{{ old('fecha_nacimiento') }}" placeholder="2001-05-15" id="fecha" class="form-control">
		                        @error('fecha_nacimiento')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		                </div>

		                  <div class="form-group">
			                    <label class="col-md-3 control-label">Seleccione Foto</label>
			                    <div class="col-md-9">
			                        <span class="pull-left btn btn-primary btn-file">
			                        Cargar Foto... <input type="file" required="" name="foto">
			                        </span>
			                    </div>

			                    @error('foto')
		                       		 <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
			                </div>

		
		         
							              
					
					           
					
					              
					               
					 <div class="modal-footer">
	                    <a href="{{ route('usuario.index') }}" class="btn btn-default" type="button">Close</a>
	                    <input type="submit" class="btn btn-primary"  onclick="return confirm('Desea Agregar?')" value="Crear Usuario" name="">
                    
               		 </div>

resources/views/users/index.blade.php
@extends('layouts.plantilla')

@section('mensaje')

	
	  @if(Session::has('Mensaje'))  
	      <div class="alert alert-warning alert-dismissible mt-3">
	        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
	        <h5><i class="icon fas fa-warning"></i> Alert!</h5>
	        {{ Session::get('Mensaje') }}
	      </div>
	    @endif
@endsection
@section('content')

 <div class="row gutter-xs">
            <div class="col-xs-12">
              <div class="card">
                <div class="card-header">
                  <div class="card-actions">
                   <a href="{{ route('usuario.create') }}" class="btn btn-outline-warning" >Agregar</a> 
             	 </div>
                   
                  </div>
                  <strong>Mantenimiento de Usuarios</strong>
                </div>
                <div class="card-body">
                  <table id="demo-datatables-5" class="table table-striped table-bordered table-nowrap dataTable" cellspacing="0" width="100%">
                    <thead>
                      <tr>
                      <th>Rol</th>                                 
                      <th >Nombres</th>
                      <th >Email</th>
                      <th>Dni</th>
                      <th>Sexo</th>
                      <th>Direccion</th>
                      <th>Telefono</th>
                      <th>Estado</th>
                      <th>Foto</th>
                      <th>Eliminar</th>
                      <th>Editar</th>
                      </tr>
                    </thead>
                    <tbody>
                       @foreach($leer as $recorrer)
                          <tr>
                              <td>{{ isset($recorrer->rol->japo_nombre) ? $recorrer->rol->japo_nombre : '' }}</td>
                              <td>{{ $recorrer->name }}</td>
                              <td>{{ $recorrer->email }}</td>
                              <td>{{ $recorrer->dni }}</td>
                              <td>{{ $recorrer->sexo }}</td>
                              <td>{{ $recorrer->direccion }}</td>
                              <td>{{ $recorrer->telefono }}</td>
                              <td>{{ $recorrer->estado }}</td>
                              <td><img src="{{ asset('storage'.'/'.$recorrer->foto) }}" width="50" class="img-thumbnail"></td>
                              <td>
                                  <form action="{{ route('usuario.destroy',$recorrer->id) }}" method="post">
                                      @csrf
                                      @method('DELETE')
                                        <button class="btn " style="border:none; background:white;" onclick="return confirm('Desea Eliminar?')">
                                           <span class="icon icon-trash"></span>
                                           <span class="caption">Delete</span>

                                        </button>
                                  </form> 
                                  
                              </td>
                              <td>  
                               

                              
                             
                                  <a class="btn btn-info btn-icon" href="{{ route('usuario.edit',$recorrer->id) }}">
                                   <span class="icon icon-edit"></span>
                                <span class="caption">edit</span>
                                 
                                  </a>
                              </td>

                          </tr>
                          @endforeach
                    </tbody>
                  
                  </table>
                </div>
              </div>
            </div>
          </div>



@endsection