routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes([
	'register' => false,
	
]);

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/galleta',function(){
	return view('layouts.plantilla');
});


Route::resource('rol','RolController');
Route::resource('autor','AutorController');
Route::resource('editorial','EditorialController');
Route::resource('libro','LibroController');
Route::resource('/usuario','UsuarioController');
Route::post('/porcentajea','PorcentajeController@aumentar')->name('porcentajeall.aumentar');
Route::post('/porcentajed','PorcentajeController@disminuir')->name('porcentajeall.disminuir');
Route::resource('aumentopreciolibro','AumentoPrecioController')->except(['create','store','destroy','show']);
Route::resource('restapreciolibro','RestaPrecioController')->except(['create','store','destroy','show']);

resources/views/autores/create.blade.php
@extends('layouts.plantilla')


@section('content')


     <div class="col-lg-12 ">
          <div class="panel">
              <div class="panel-heading">
                  <h3 class="panel-title bg-warning" style="color:#fff">Agregar Informacion del Autor</h3>
              </div>
  
  
              <!-- BASIC FORM ELEMENTS -->
          <form action="{{ route('autor.store') }}" onsubmit="return esfechavalida() " method="post" name="forma" class="panel-body form-horizontal form-padding">
                    @csrf
                    <!--Static-->
                    @include('autores.formAutor',['mensaje'=> 'crear'])
                                
                 </form>
              <!--===================================================-->
              <!-- END BASIC FORM ELEMENTS -->
  
  
          </div>
      </div>
@endsection

resources/views/autores/edit.blade.php
@extends('layouts.plantilla')

@section('mensaje')

	

@section('content')
      <div class="col-lg-12 ">
              <div class="panel">
                  <div class="panel-heading">
                      <h3 class="panel-title">Editar Informacion del Autor</h3>
                  </div>
      
      
                  <!-- BASIC FORM ELEMENTS -->
                  <!--===================================================-->
                  <form  action="{{ route('autor.update', $actualizar->id) }}" onsubmit="return esfechavalida() " name="forma" id="form1" method="post" class="panel-body form-horizontal form-padding">
                    @csrf
                    @method('PUT')
      
                 <div class="form-group">
                    <label class="col-md-3 control-label" for="demo-text-input">Nombres</label>
                        <div class="col-md-9">
                            <input type="text" name="japo_nombres" value="{{ isset($actualizar->japo_nombres) ? $actualizar->japo_nombres : '' }}" id="demo-text-input" class="form-control" placeholder="Nombres">
                            @error('japo_nombres')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                    </div>
    
                    <!--Text Input-->
                    <div class="form-group">
                        <label class="col-md-3 control-label" for="demo-text-input">Apellidos</label>
                        <div class="col-md-9">
                            <input type="text" name="japo_apellidos" value="{{ isset($actualizar->japo_apellidos) ? $actualizar->japo_apellidos : ''  }}" id="demo-text-input" class="form-control" placeholder="Apellidos">
                            @error('japo_apellidos')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                    </div>
    
                    <!--Email Input-->
                    <div class="form-group">
                        <label class="col-md-3 control-label" for="demo-email-input">Tipo DNI</label>
                        <div class="col-md-9">
                            <select name="japo_tipo_dni" class="form-control">
                              <option>Seleccion tipo de dni</option>  
                              <option value="C" @if($actualizar->japo_tipo_dni == 'C') selected=""  @endif) >Cedula Ciudadania</option>
                              <option value="P" @if($actualizar->japo_tipo_dni == 'P') selected=""  @endif) >Pasaporte</option>
                            </select>
                             @error('japo_tipo_dni')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                    </div>

                     <div class="form-group">
                        <label class="col-md-3 control-label" for="demo-text-input">Dni</label>
                        <div class="col-md-9">
                            <input type="number" id="documento" onblur="validarDocumento()" name="japo_dni"  onKeyPress="return soloNumeros(event)" value="{{ isset($actualizar->japo_dni) ? $actualizar->japo_dni : ''  }}" id="demo-text-input" class="form-control" placeholder="Ingrese Dni">
                             @error('japo_dni')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label" for="demo-email-input">Sexo</label>
                        <div class="col-md-9">
                            <select name="japo_sexo" class="form-control">
                              <option>Seleccion tipo de sexo</option> 
                              <option value="H" @if($actualizar->japo_sexo == 'H') selected=""  @endif) >Hombre</option>
                              <option value="M" @if($actualizar->japo_sexo == 'M') selected=""  @endif) >Mujer</option>
                            </select>
                            @error('japo_sexo')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                    </div>

                     <div class="form-group">
                        <label class="col-md-3 control-label" for="demo-text-input">Fecha Nacimiento</label>
                        <div class="col-md-9">
                            <input type="text" id="fecha" onblur="esfechavalida();" name="japo_fecha_autor" value="{{ isset($actualizar->japo_fecha_autor) ? $actualizar->japo_fecha_autor : ''  }}"  id="demo-text-input" class="form-control" placeholder="Ingrese Email">
                            @error('japo_fecha_autor')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                    </div>
    

                     <div class="form-group">
                        <label class="col-md-3 control-label" for="demo-text-input">Email</label>
                        <div class="col-md-9">
                            <input type="text" name="japo_email" value="{{ isset($actualizar->japo_email) ? $actualizar->japo_email : ''  }}"   id="demo-text-input" class="form-control" placeholder="Ingrese Email">
                            @error('japo_email')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label" for="demo-email-input">Estado</label>
                        <div class="col-md-9">
                            <select name="japo_estado" class="form-control">
                              <option>Seleccion de estado</option>  
                              <option value="A" @if($actualizar->japo_estado == 'A') selected=""  @endif) >Activo</option>
                              <option value="I" @if($actualizar->japo_estado == 'I') selected=""  @endif) >Inactivo</option>
                            </select>
                            @error('japo_estado')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                    </div>
          
                        
          
                        
          
                        
                         
           <div class="modal-footer">
                      <a href="{{ route('autor.index') }}" class="btn btn-default" type="button">Close</a>
                      <input type="submit" id="Guardar" class="btn btn-primary"  onclick="return confirm('Desea Actualizar?')" value="Actualizar Actor" name="">
                    
                   </div>
                  </form>
                  <!--===================================================-->
                  <!-- END BASIC FORM ELEMENTS -->
      
      
              </div>
          </div>  


@endsection

resources/views/autores/formAutor.blade.php
@include("recursos.validacion")



  					 <div class="form-group">
		                <label class="col-md-3 control-label" for="demo-text-input">Nombres</label>
		                    <div class="col-md-9">
		                        <input type="text" required=""  id="nombres" value="{{ old('japo_nombres') }}" name="japo_nombres"  id="demo-text-input" class="form-control" placeholder="Nombres">
		                        @error('japo_nombres')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		                </div>
		
		                <!--Text Input-->
		                <div class="form-group">
		                    <label class="col-md-3 control-label" for="demo-text-input">Apellidos</label>
		                    <div class="col-md-9">
		                        <input type="text"  id="apellidos" value="{{ old('japo_apellidos') }}" name="japo_apellidos" id="demo-text-input" class="form-control" placeholder="Apellidos">
		                        @error('japo_apellidos')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		                </div>
		
		                <!--Email Input-->
		                <div class="form-group">
		                    <label class="col-md-3 control-label" for="demo-email-input">Tipo DNI</label>
		                    <div class="col-md-9">
		                        <select required="" name="japo_tipo_dni" class="form-control">
		                        	<option value="">Seleccion tipo de dni</option>	
		                        	<option value="C" >Cedula Ciudadania</option>
		                        	<option value="P" >Pasaporte</option>
		                        </select>

		                        @error('japo_tipo_dni')
									<span class="invalid-feedback d-block" role="alert">
										{{ $message }}
									</span>
									
								@enderror	
		                        
		                    </div>
		                </div>

		                 <div class="form-group">
		                    <label class="col-md-3  control-label" for="demo-text-input">Dni</label>
		                    <div class="col-md-9">
		                        <input type="number" value="{{ old('japo_dni') }}" required="" id="documento" onblur="validarDocumento()" name="japo_dni"  onKeyPress="return soloNumeros(event)"  id="demo-text-input" class="form-control" placeholder="Ingrese Dni">
		                         @error('japo_dni')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		                </div>

		                <div class="form-group">
		                    <label class="col-md-3 control-label" for="demo-email-input">Sexo</label>
		                    <div class="col-md-9">
		                        <select required="" name="japo_sexo" class="form-control">
		                        	<option value="">Seleccion tipo de sexo</option>	
		                        	<option value="H">Hombre</option>
		                        	<option value="M">Mujer</option>
		                        </select>

	                           @error('japo_sexo')
								<span class="invalid-feedback d-block" role="alert">
									{{ $message }}
								</span>
								@enderror	
		                       
		                    </div>
		                </div>

		                 <div class="form-group">
		                    <label class="col-md-3 control-label" for="demo-text-input">Fecha Nacimiento(yyyy-mm-dd)</label>
		                    <div class="col-md-9">
		                        <input type="text" required=""  id="fecha" value="{{ old('japo_fecha_autor') }}"  name="japo_fecha_autor"   id="demo-text-input" class="form-control" placeholder="Ingrese fecha">
		                        @error('japo_fecha_autor')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		                </div>
		

		                 <div class="form-group">
		                    <label class="col-md-3 control-label" for="demo-text-input">Email</label>
		                    <div class="col-md-9">
		                        <input type="text" required="" id="email" value="{{ old('japo_email') }}" name="japo_email"    id="demo-text-input" class="form-control" placeholder="Ingrese Email">
		                        @error('japo_email')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		                </div>         
								              
								              
					               
					<div class="modal-footer">
	                    <a href="{{ route('autor.index') }}" class="btn btn-default" type="button">Close</a>
	                    <input type="submit"  class="btn btn-primary"  onclick="return confirm('Desea Agregar?')" value="Crear Actor" name="">
                    
               		 </div>

               		

               		

resources/views/autores/index.blade.php
@extends('layouts.plantilla')

@section('mensaje')

	
	  @if(Session::has('Mensaje'))  
	      <div class="alert alert-warning alert-dismissible mt-3">
	        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
	        <h5><i class="icon fas fa-warning"></i> Alert!</h5>
	        {{ Session::get('Mensaje') }}
	      </div>
	    @endif
@endsection
@section('content')

 <div class="row gutter-xs">
            <div class="col-xs-12">
              <div class="card">
                <div class="card-header">
                  <div class="card-actions">
                <a href="{{ route('autor.create') }}" class="btn btn-outline-warning ">Agregar</a>
             	 </div>
                   
                  </div>
                  <strong>Mantenimiento de Autores</strong>
                </div>
                <div class="card-body">
                  <table id="demo-datatables-5" class="table table-striped table-bordered table-nowrap dataTable" cellspacing="0" width="100%">
                    <thead>
                      <tr>
                        <th>Nombres y Apellidos</th>                                 
                        <th >DNI.</th>
                        <th >Sexo</th>
                        <th >Fecha Nacim.</th>
                        <th >Email</th>
                        <th >Estado</th>
                        <th>Eliminar</th>
                        <th>Editar</th>
                      </tr>
                    </thead>
                    <tbody>
                     @foreach($leer as $recorrer)
                        <tr>
                            <td>{{ $recorrer->japo_nombres }} {{ $recorrer->japo_apellidos }}</td>                               
                            <td>{{ $recorrer->japo_dni }}</td>
                            <td>{{ $recorrer->japo_sexo }}</td>
                            <td>{{ $recorrer->japo_fecha_autor }}</td>
                            <td>{{ $recorrer->japo_email }}</td>
                            <td>{{ $recorrer->japo_estado }}</td>

                            <td>
                                <form action="{{ route('autor.destroy',$recorrer->id) }}" method="post">
                                    @csrf
                                    @method('DELETE')
                                      <button class="btn btn" style="border:none; background:white;" onclick="return confirm('Desea Eliminar?')">
                                      	
					                      <span class="icon icon-trash"></span>
					                      <span class="caption">trash</span>
					                    
                                      </button>
                                     
                                </form> 
                                
                            </td>
                            <td>  
                             

                                                     
                                <a class="btn btn-info btn-icon" href="{{ route('autor.edit',$recorrer->id) }}">   <span class="icon icon-edit"></span>
                     			      <span class="caption">edit</span>
                     			    </a>
                            </td>

                        </tr>
                        @endforeach
                    </tbody>
                  
                  </table>
                </div>
              </div>
            </div>
          </div>



@endsection