routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes([
	'register' => false,
	
]);

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/galleta',function(){
	return view('layouts.plantilla');
});


Route::resource('rol','RolController');
Route::resource('autor','AutorController');
Route::resource('editorial','EditorialController');
Route::resource('libro','LibroController');
Route::resource('/usuario','UsuarioController');
Route::post('/porcentajea','PorcentajeController@aumentar')->name('porcentajeall.aumentar');
Route::post('/porcentajed','PorcentajeController@disminuir')->name('porcentajeall.disminuir');
Route::resource('aumentopreciolibro','AumentoPrecioController')->except(['create','store','destroy','show']);
Route::resource('restapreciolibro','RestaPrecioController')->except(['create','store','destroy','show']);

app/Libro.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Libro extends Model
{
    //LARAVEL ADMITIRA SOLO ESTOS CAMPOS EN  EL INGRESO DEL FORMULARIO PARA LA TABLA LIBRO EVITANDO ATAQUES SQL
    protected $fillable=['autor_id','editorial_id','japo_ISBN','japo_titulo','japo_anio','japo_precio_venta','japo_otros_autores','japo_estado'];

    //RELACION  DE UNO A MUCHOS

    public function autor(){
        return $this->belongsTo('App\Autor');
    }
    //RELACION  DE UNO A MUCHOS

    public function editorial(){
    	return $this->belongsTo('App\Editorial');
    }

}

app/Http/Controllers/LibroController.php
<?php

namespace App\Http\Controllers;


use App\Editorial;
use App\Autor;
use App\Libro;
use Illuminate\Http\Request;

class LibroController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    
   public function index()
    {
        $libro = Libro::all();
        $leer = $libro;

        $autor = Autor::all();
        $autores = $autor;

          $autor = Autor::all();
        $autores = $autor;

        $editorial = Editorial::all();
        $editoriales = $editorial;
        return view('libros.index',compact('leer','autores','editoriales'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       
      $autor = Autor::all();
        $autores = $autor;

        $editorial = Editorial::all();
        $editoriales = $editorial;
        return view('libros.create',compact('autores','editoriales'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $datos = [
            'autor_id' => 'required | ',
            'editorial_id' => 'required',
            'japo_ISBN' => 'required | unique:libros',
            'japo_titulo' => 'required | min:5 | max:20 | string',
            'japo_anio' => 'required | min: 4 | max:4| ',
            'japo_precio_venta' => 'required|max:22|regex:/^-?[0-9]+(?:\.[0-9]{1,2})?$/',
            'japo_otros_autores' => 'max:50|regex:/(^[A-Za-z0-9-, ]+$)+/'

        ];
      
      $this->validate($request,$datos);
        $datosLibro=request()->except('_token');

          $datosLibro['japo_titulo'] = strtoupper($request->get('japo_titulo'));
          $datosLibro['japo_otros_autores'] = strtoupper($request->get('japo_otros_autores'));

        
         
        Libro::insert($datosLibro);
       
        return redirect('libro')->with([
            'Mensaje' => 'Libro Agregado'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Libro  $libro
     * @return \Illuminate\Http\Response
     */
    public function show(Libro $libro)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Libro  $libro
     * @return \Illuminate\Http\Response
     */
    public function edit( $id)
    {
        $autor = Autor::all();
        $autores = $autor;

        $editorial = Editorial::all();
        $editoriales = $editorial;

        $actualizar = Libro::findOrFail($id);
        return view('libros.edit',compact('actualizar','autores','editoriales'));
    
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Libro  $libro
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,  $id)
    {
       
        $datos = [
            'autor_id' => 'required | ',
            'editorial_id' => 'required',
            'japo_ISBN' => 'required ',
            'japo_titulo' => 'required | min:5 | max:20 | string  |',
            'japo_anio' => 'required | min: 4| max:4| alpha_num',
            'japo_precio_venta' => 'required|max:22|regex:/^-?[0-9]+(?:\.[0-9]{1,2})?$/',
            'japo_otros_autores' => 'max:50|regex:/(^[A-Za-z0-9-, ]+$)+/',
            'japo_estado' => 'required'

        ];
      
      $this->validate($request,$datos);


       $datosLibro = request()->except('_token','_method'); 
       $datosLibro['japo_titulo'] = strtoupper($request->get('japo_titulo'));
       $datosLibro['japo_otros_autores'] = strtoupper($request->get('japo_otros_autores'));
        
       Libro::whereId($id)->update($datosLibro);
       
       return redirect("libro")->with([
        'Mensaje' => 'Libro actualizado'
       ]);    
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Libro  $libro
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Libro::whereId($id)->delete();
       
        return redirect('/libro')->with([
        'Mensaje' => 'Libro Eliminado',
         ]);
    }
}

resources/views/libros/AumentaPrecioLibro.blade.php
@extends('layouts.plantilla')



  

@section('content')
  
      <div class="col-lg-12 ">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">Aumentar precio del libro  {{ $actualizar->japo_titulo }}
                  Valor $ {{ $actualizar->japo_precio_venta }}
                </h3>

            </div>


       
            <!--===================================================-->
            <form  action="{{ route('aumentopreciolibro.update', $actualizar->id) }}" onsubmit="return validacionPorcentaje()"  method="post" class="panel-body form-horizontal form-padding">
              @csrf
              @method('PUT')
              @include('libros.formAumentarPorcentaje',['mensaje'=>'aumentar'])
             </div>
            </form>
            <!--===================================================-->
            <!-- END BASIC FORM ELEMENTS -->


        </div>
    </div>

@endsection

resources/views/libros/RestaPrecioLibro.blade.php
@extends('layouts.plantilla')



  

@section('content')
  
     <div class="col-lg-12 ">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">Restar valor del libro {{ $actualizar->japo_titulo }}
                  Valor $ {{ $actualizar->japo_precio_venta }}
                </h3>

            </div>


       
            <!--===================================================-->
            <form  action="{{ route('restapreciolibro.update', $actualizar->id) }}"   method="post" class="panel-body form-horizontal form-padding">
              @csrf
              @method('PUT')
              @include('libros.formDisminuirPorcentaje',['mensaje'=>'restar'])
             </div>
            </form>
            <!--===================================================-->
            <!-- END BASIC FORM ELEMENTS -->


        </div>
    </div>

@endsection

resources/views/libros/create.blade.php
@extends('layouts.plantilla')



@section('content')

      <div class="col-lg-12 ">
              <div class="panel">
                <div class="panel-heading">
                    <h3 class="panel-title">Agregar Informacion del libro</h3>
                </div>
      
      
             
                  <form action="{{ route('libro.store') }}" onsubmit="return validacionLibro()" method="post" class="panel-body form-horizontal form-padding">
                        @csrf
                        <!--Static-->
                        @include('libros.formLibro',['mensaje'=> 'crear'])
                                    
                  </form>
      
              </div>
          </div>


@endsection

resources/views/libros/edit.blade.php
@extends('layouts.plantilla')



@section('content')
      
    <div class="col-lg-12 ">
              <div class="panel">
                  <div class="panel-heading">
                      <h3 class="panel-title bg-primary">Editar Informacion del libro</h3>
                  </div>
      
      
             
                  <!--===================================================-->
                  <form  action="{{ route('libro.update', $actualizar->id) }}"  method="post" class="panel-body form-horizontal form-padding">
                    @csrf
                    @method('PUT')


               
           


               <div class="form-group">
                  <label class="col-md-3 control-label" for="demo-text-input">Autor</label>
                      <div class="col-md-9">
                          <select class="form-control" name="autor_id">
                            @forelse($autores as $autor)
                            
                              <option value="{{ $autor->id }}" @if($autor->id == $actualizar->autor_id) selected="" @endif>{{ $autor->japo_nombres. ' '.$autor->japo_apellidos }}</option>
                            @empty
                            <span class="text-danger">No se encontraron roles</span>

                            @endforelse
                          </select>
                          @error('autor_id')
                          <small class="help-block text-danger">{{ $message }}</small>
                          @enderror
                      </div>
                 </div> 


         
                 <div class="form-group">
                    <label class="col-md-3 control-label" for="demo-text-input">Seleccione Editorial</label>
                        <div class="col-md-9">
                            <select class="form-control" name="editorial_id">
                              @forelse($editoriales as $editorial)
                              
                                <option value="{{ $editorial->id }}" @if($editorial->id == $actualizar->editorial_id) selected="" @endif>{{ $editorial->japo_nombre }}</option>


                              @empty
                              <span class="text-danger">No se encontraron roles</span>

                              @endforelse
                            </select>
                            @error('editorial_id')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                 </div>

      
                  <div class="form-group">
                        <label class="col-md-3 control-label" for="demo-text-input">ISBN</label>
                          <div class="col-md-9">
                              <input type="text" required="" name="japo_ISBN" id="isbn" onblur="run()" value="{{ isset($actualizar->japo_ISBN) ? $actualizar->japo_ISBN : '' }}" id="demo-text-input" class="form-control" placeholder="Ingrese ISBN">
                              @error('japo_ISBN')
                              <small class="help-block text-danger">{{ $message }}</small>
                              @enderror
                          </div>
                    </div>
    
                  

                     <div class="form-group">
                        <label class="col-md-3 control-label" for="demo-text-input">Titulo</label>
                        <div class="col-md-9">
                            <input type="text" id="titulo" name="japo_titulo" value="{{ isset($actualizar->japo_titulo) ? $actualizar->japo_titulo : ''  }}"   id="demo-text-input" class="form-control" placeholder="Ingrese titulo">
                            @error('japo_titulo')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                    </div>

                     <div class="form-group">
                        <label class="col-md-3 control-label" for="demo-text-input">Año</label>
                        <div class="col-md-9">
                            <input type="text" id="anio" name="japo_anio" value="{{ isset($actualizar->japo_anio) ? $actualizar->japo_anio : ''  }}"   id="demo-text-input" class="form-control" placeholder="Ingrese Año del libro">
                            @error('japo_anio')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                    </div>

                     <div class="form-group">
                        <label class="col-md-3 control-label" for="demo-text-input">Precio de venta</label>
                        <div class="col-md-9">
                            <input type="text" id="precio" name="japo_precio_venta" value="{{ isset($actualizar->japo_precio_venta) ? $actualizar->japo_precio_venta : ''  }}"   id="demo-text-input" class="form-control" placeholder="Ingrese Precio de venta">
                            @error('japo_precio_venta')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                    </div>

                       <div class="form-group">
                        <label class="col-md-3 control-label" for="demo-text-input">Otros autores</label>
                        <div class="col-md-9">
                            <input  name="japo_otros_autores"  style="resize: none" value="{{ isset($actualizar->japo_otros_autores) ? $actualizar->japo_otros_autores : ''  }}"   id="demo-text-input" class="form-control" placeholder="Ingrese otros autores">
                            @error('japo_otros_autores')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label" for="demo-email-input">Estado</label>
                        <div class="col-md-9">
                            <select name="japo_estado" class="form-control">
                              <option>Seleccion de estado</option>  
                              <option value="A" @if($actualizar->japo_estado == 'A') selected=""  @endif) >Activo</option>
                              <option value="I" @if($actualizar->japo_estado == 'I') selected=""  @endif) >Inactivo</option>
                            </select>
                            @error('japo_estado')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                    </div>
          
                        
          
                        
          
                        
                         
           <div class="modal-footer">
                      <a href="{{ route('libro.index') }}" class="btn btn-default" type="button">Close</a>
                      <input type="submit" class="btn btn-primary"  onclick="return confirm('Desea Actualizar?')" value="Actualizar Libro" name="">
                    
                   </div>
                  </form>
                  <!--===================================================-->
                  <!-- END BASIC FORM ELEMENTS -->
      
      
              </div>
    </div>



@endsection

resources/views/libros/formAumentarPorcentaje.blade.php
        <div class="form-group">
             <label class="col-md-4 control-label" for="demo-text-input">Porcentaje</label>
            <div class="col-md-8">
                <input type="text" required="" name="japo_porcentaje"  id="porcentaje"  class="form-control" placeholder="Ingrese Procentaje">
                @error('japo_porcentaje')
                <small class="help-block text-danger">{{ $message }}</small>
                @enderror
            </div>

             <div class="col-md-8">
                <input type="hidden" name="japo_titulo"  value="{{ $actualizar->japo_titulo }}" id="demo-text-input" class="form-control" placeholder="Ingrese Procentaje Ejem. 10,20">
                @error('japo_titulo')
                <small class="help-block text-danger">{{ $message }}</small>
                @enderror
            </div>

        </div>

         <div class="modal-footer">
            <a href="{{ route('libro.index') }}" class="btn btn-default" type="button">Close</a>
            <input type="submit" onclick="return confirm('Desea cambiar el porcentaje?')" class="btn btn-warning"  value="{{ $mensaje === 'aumentar' ? 'Aumentar ' : ' Disminuir' }} Porcentaje del libro" name="">
        
        </div>

resources/views/libros/formAumentarPorcentajeAll.blade.php
		<div class="form-group">
       		 <label class="col-md-4 control-label" for="demo-text-input">Porcentaje </label>
            <div class="col-md-8">
                <input type="number"   name="japo_porcentaje"  required=""   id="porcentaje" class="form-control" placeholder="Ingrese Procentaje ejem. 10,20">
                @error('japo_porcentaje')
                <small class="help-block text-danger">{{ $message }}</small>
                @enderror
            </div>
        </div>

         <div class="modal-footer">
            <button data-dismiss="modal" class="btn btn-default" type="button">Close</button>
            <input type="submit"  class="btn btn-warning"  value="Aumentar Porcentaje a todos los  libros" name="">
        
   		 </div>

resources/views/libros/formDisminuirPorcentaje.blade.php
        <div class="form-group">
             <label class="col-md-4 control-label" for="demo-text-input">Porcentaje</label>
            <div class="col-md-8">
                <input type="text" required="" name="japo_porcentaje"  id="porcentaje"  class="form-control" placeholder="Ingrese Procentaje Ejem. 10,20">
                @error('japo_porcentaje')
                <small class="help-block text-danger">{{ $message }}</small>
                @enderror
            </div>

             <div class="col-md-8">
                <input type="hidden" name="japo_titulo"  value="{{ $actualizar->japo_titulo }}" id="demo-text-input" class="form-control" placeholder="Ingrese Procentaje">
                @error('japo_titulo')
                <small class="help-block text-danger">{{ $message }}</small>
                @enderror
            </div>

        </div>

         <div class="modal-footer">
            <a href="{{ route('libro.index') }}" class="btn btn-default" type="button">Close</a>
            <input type="submit" onclick="return confirm('Desea cambiar el porcentaje?')" class="btn btn-warning"  value="{{ $mensaje === 'aumentar' ? 'Aumentar ' : ' Disminuir' }} Porcentaje del libro" name="">
        
        </div>

resources/views/libros/formRestarrPorcentajeAll.blade.php
		<div class="form-group">
       		 <label class="col-md-4 control-label" for="demo-text-input">Porcentaje</label>
            <div class="col-md-8">
                <input type="text" required="" name="japo_porcentaje"    class="form-control" placeholder="Ingrese Procentaje Ejem. 10,20">
                @error('japo_porcentaje')
                <small class="help-block text-danger">{{ $message }}</small>
                @enderror
            </div>
        </div>

         <div class="modal-footer">
            <button data-dismiss="modal" class="btn btn-default" type="button">Close</button>
            <input type="submit" onclick="return confirm('Desea cambiar el porcentaje?')" class="btn btn-warning"  value=" Disminuir Porcentaje del libro" name="">
        
   		 </div>

resources/views/libros/index.blade.php
@extends('layouts.plantilla')

@section('mensaje')

  
    @if(Session::has('Mensaje'))  
        <div class="alert alert-warning alert-dismissible mt-3">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <h5><i class="icon fas fa-warning"></i> Alert!</h5>
          {{ Session::get('Mensaje') }}
        </div>
      @endif
@endsection
@section('content')

 <div class="row gutter-xs">
            <div class="col-xs-12">
              <div class="card">
                <div class="card-header">
                  <div class="card-actions">
                 <a href="{{ route('libro.create') }}" class="btn btn-outline-warning">Agregar</a>
                  @auth 
                    @if(Auth::user()->rol->japo_nombre == 'ADMINISTRADOR') 
                      <button data-target="#modal-sumar" data-toggle="modal" class="btn btn-info btn-rounded">Aumentar Precio</button>

                      <button data-target="#modal-restar" data-toggle="modal" class="btn btn-danger btn-rounded">Restar Precio
                      </button>
                    @endif
                  @endauth   

               </div>
                   
                  </div>
                  <strong>Mantenimiento de Libros</strong>
                </div>
                <div class="card-body">
                  <table id="demo-datatables-5" class="table table-striped table-bordered table-nowrap dataTable" cellspacing="0" width="100%">
                    <thead>
                      <tr>
                        <th>Autor</th>  
                        <th>Editorial</th>                                
                        <th >ISBN</th>
                        <th >Titulo</th>
                        <th >Año</th>
                        <th >Precio de venta</th>
                        <th >Otros autores</th>
                        <th>Eliminar</th>
                        <th>Editar</th>

                         @auth @if(Auth::user()->rol->japo_nombre == 'ADMINISTRADOR')

                         <th>Porcentaje</th>
                        @endif
                        @endauth
                      </tr>
                    </thead>
                    <tbody>
                     @foreach($leer as $recorrer)
                        <tr>
                             <td> {{ isset($recorrer->autor->japo_nombres) ? $recorrer->autor->japo_nombres .' '. $recorrer->autor->japo_apellidos   : '' }} 
                                        </td>
                                        <td>{{ isset($recorrer->editorial->japo_nombre) ? $recorrer->editorial->japo_nombre : '' }}
                                        </td>

                                        <td>{{ $recorrer->japo_ISBN }}</td>
                                        <td>{{ $recorrer->japo_titulo }}</td>
                                        <td>{{ $recorrer->japo_anio }}</td>
                                        <td>{{ $recorrer->japo_precio_venta }}</td>
                                        <td>{{ $recorrer->japo_otros_autores }}</td>

                            <td>
                                <form action="{{ route('libro.destroy',$recorrer->id) }}" method="post">
                                    @csrf
                                    @method('DELETE')
                                      <button class="btn btn" style="border:none; background:white;" onclick="return confirm('Desea Eliminar?')">
                                        
                                <span class="icon icon-trash"></span>
                                <span class="caption">trash</span>
                              
                                      </button>
                                     
                                </form> 
                                
                            </td>
                            <td>  
                             
                                                   
                                <a class="btn btn-info btn-icon" href="{{ route('libro.edit',$recorrer->id) }}">   <span class="icon icon-edit"></span>
                                <span class="caption">edit</span>
                              </a>
                            </td>

                             @if(Auth::user()->rol->japo_nombre == 'ADMINISTRADOR')

                                  <td>
                                      <a href="{{ route('aumentopreciolibro.edit',$recorrer->id) }}" class="btn">
                                            <span class="icon icon-chevron-circle-up"></span>
                     
                                      </a>
                                  @if($recorrer->japo_precio_venta > 1)    
                                      <a href="{{ route('restapreciolibro.edit',$recorrer->id) }}" class="btn ">
                                        <span class="icon icon-chevron-circle-down"></span>
                                  @else
                                      <span class="text-danger">Precio muy bajo no disminuya</span>        
                                  @endif        
                                      </a>
                                  </td>
                              @endif 

                        </tr>
                        @endforeach
                    </tbody>
                  
                  </table>
                </div>
              </div>
            </div>
          </div>



         <!--modal para agregar  PRECIO A  TODOS LOS LIBROS-->

      <!-- MODALES -->

  

    <div class="modal fade" id="modal-sumar" role="dialog" tabindex="-1" aria-labelledby="demo-default-modal" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">

                <!--Modal header-->
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><i class="pci-cross pci-circle"></i></button>
                    <h4 class="modal-title text-center">Aumentar porcentaje a todos los Libros </h4>
                </div>

                <!--Modal body-->
                <div class="modal-body">
                     <form action="{{ route('porcentajeall.aumentar') }}"  method="post" class="panel-body form-horizontal form-padding">
                        @csrf
                        <!--Static-->
                        @include('libros.formAumentarPorcentajeAll')
                                    
                     </form>
                   
                </div>

                <!--Modal footer-->
             
            </div>
        </div>
    </div>

     <div class="modal fade" id="modal-restar" role="dialog" tabindex="-1" aria-labelledby="demo-default-modal" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">

                <!--Modal header-->
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><i class="pci-cross pci-circle"></i></button>
                    <h4 class="modal-title text-center">Disminuir porcentaje a todos los Libros </h4>
                </div>

                <!--Modal body-->
                <div class="modal-body">
                     <form action="{{ route('porcentajeall.disminuir') }}" onsubmit="return validacionPorcentaje()"  method="post" class="panel-body form-horizontal form-padding">
                        @csrf
                        <!--Static-->
                        @include('libros.formRestarrPorcentajeAll')
                                    
                     </form>
                   
                </div>

                <!--Modal footer-->
             
            </div>
        </div>
    </div>
@endsection