routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes([
	'register' => false,
	
]);

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/galleta',function(){
	return view('layouts.plantilla');
});


Route::resource('rol','RolController');
Route::resource('autor','AutorController');
Route::resource('editorial','EditorialController');
Route::resource('libro','LibroController');
Route::resource('/usuario','UsuarioController');
Route::post('/porcentajea','PorcentajeController@aumentar')->name('porcentajeall.aumentar');
Route::post('/porcentajed','PorcentajeController@disminuir')->name('porcentajeall.disminuir');
Route::resource('aumentopreciolibro','AumentoPrecioController')->except(['create','store','destroy','show']);
Route::resource('restapreciolibro','RestaPrecioController')->except(['create','store','destroy','show']);

resources/views/editoriales/create.blade.php
@extends('layouts.plantilla')


@section('content')


      <div class="col-lg-12 ">
          <div class="panel">
              <div class="panel-heading">
                  <h3 class="panel-title bg-warning">Agregar Informacion de la Editorial</h3>
              </div>
  
  
              <!-- BASIC FORM ELEMENTS -->
              <!--===================================================-->
           <form action="{{ route('editorial.store') }}" onsubmit="return validacionEditorial()" method="post" class="panel-body form-horizontal form-padding">
                    @csrf
                    <!--Static-->
                    @include('editoriales.formEditorial')
                                
                 </form>
              <!--===================================================-->
              <!-- END BASIC FORM ELEMENTS -->
  
  
          </div>
      </div>
   

@endsection

resources/views/editoriales/edit.blade.php
@extends('layouts.plantilla')

@section('mensaje')

	

@section('content')
  

   <div class="col-lg-12 ">
              <div class="panel">
                  <div class="panel-heading">
                      <h3 class="panel-title">Editar Informacion de la Editorial</h3>
                  </div>
      
      
                  <!-- BASIC FORM ELEMENTS -->
                  <!--===================================================-->
                  <form  action="{{ route('editorial.update', $datoIndividual->id) }}" method="post" class="panel-body form-horizontal form-padding">
                    @csrf
                    @method('PUT')
      
                                 <div class="form-group">
                    <label class="col-md-3 control-label" for="demo-text-input">Nombre Editorial</label>
                        <div class="col-md-9">
                            <input type="text" id="editorial" name="japo_nombre" value="{{ isset($datoIndividual->japo_nombre) ? $datoIndividual->japo_nombre : '' }}" id="demo-text-input" class="form-control" placeholder="Ingrese nombre editorial">
                            @error('japo_nombre')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                    </div>
    
                  

                     <div class="form-group">
                        <label class="col-md-3 control-label" for="demo-text-input">Email</label>
                        <div class="col-md-9">
                            <input type="text" id="email" name="japo_email" value="{{ isset($datoIndividual->japo_email) ? $datoIndividual->japo_email : ''  }}"   id="demo-text-input" class="form-control" placeholder="Ingrese Email">
                            @error('japo_email')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label" for="demo-email-input">Estado</label>
                        <div class="col-md-9">
                            <select name="japo_estado" class="form-control">
                              <option>Seleccion de estado</option>  
                              <option value="A" @if($datoIndividual->japo_estado == 'A') selected=""  @endif) >Activo</option>
                              <option value="I" @if($datoIndividual->japo_estado == 'I') selected=""  @endif) >Inactivo</option>
                            </select>
                            @error('japo_estado')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                    </div>
          
                        
          
                        
          
                        
                         
           <div class="modal-footer">
                      <a href="{{ route('editorial.index') }}" class="btn btn-default" type="button">Close</a>
                      <input type="submit" class="btn btn-primary"  onclick="return confirm('Desea Actualizar?')" value="Actualizar Editorial" name="">
                    
                   </div>
          </form>
                  <!--===================================================-->
                  <!-- END BASIC FORM ELEMENTS -->
      
      
              </div>
          </div>
       


@endsection

resources/views/editoriales/formEditorial.blade.php
	 <div class="form-group">
        <label class="col-md-3 control-label" for="demo-text-input">Nombre Editorial</label>
            <div class="col-md-9">
                <input type="text" id="editorial" required="" value="{{ old('japo_nombre') }}" name="japo_nombre"  id="demo-text-input" class="form-control" placeholder="Ingrese Editorial">
                @error('japo_nombre')
                <small class="help-block text-danger">{{ $message }}</small>
                @enderror
            </div>
        </div>

     
    <div class="form-group">
            <label class="col-md-3 control-label" for="demo-text-input">Email</label>
            <div class="col-md-9">
                <input type="text" id="email" required=""  value="{{ old('japo_email') }}" name="japo_email"    id="demo-text-input" class="form-control" placeholder="Ingrese Email">
                @error('japo_email')
                <small class="help-block text-danger">{{ $message }}</small>
                @enderror
            </div>
    </div>
	
	              
	
	              
	
	              
	               
	 <div class="modal-footer">
        <a href="{{ route('editorial.index') }}" class="btn btn-default" type="button">Close</a>
        <input type="submit" class="btn btn-primary"  onclick="return confirm('Desea Agregar?')" value="Crear Editorial" name="">
    
	 </div>

resources/views/editoriales/index.blade.php
@extends('layouts.plantilla')

@section('mensaje')

	
	  @if(Session::has('Mensaje'))  
	      <div class="alert alert-warning alert-dismissible mt-3">
	        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
	        <h5><i class="icon fas fa-warning"></i> Alert!</h5>
	        {{ Session::get('Mensaje') }}
	      </div>
	    @endif
@endsection
@section('content')

 <div class="row gutter-xs">
            <div class="col-xs-12">
              <div class="card">
                <div class="card-header">
                  <div class="card-actions">
                <a href="{{ route('editorial.create') }}" class="btn btn-outline-warning ">Agregar</a>
             	 </div>
                   
                  </div>
                  <strong>Mantenimiento de Editoriales</strong>
                </div>
                <div class="card-body">
                  <table id="demo-datatables-5" class="table table-striped table-bordered table-nowrap dataTable" cellspacing="0" width="100%">
                    <thead>
                      <tr>
                          <th> Editorial</th>                                 
	                      <th >Email</th>
	                      <th >Estado</th>
	                      <th>Eliminar</th>
	                      <th>Editar</th>
                      </tr>
                    </thead>
                    <tbody>
                     @foreach($editorial as $editoriales)
                        <tr>
                            <td>{{ $editoriales->japo_nombre }}</td>
                            <td>{{ $editoriales->japo_email }}</td>
                            <td>{{ $editoriales->japo_estado }}</td>

                            <td>
                                <form action="{{ route('editorial.destroy',$editoriales->id) }}" method="post">
                                    @csrf
                                    @method('DELETE')
                                      <button class="btn btn" style="border:none; background:white;" onclick="return confirm('Desea Eliminar?')">
                                      	
					                      <span class="icon icon-trash"></span>
					                      <span class="caption">trash</span>
					                    
                                      </button>
                                     
                                </form> 
                                
                            </td>
                            <td>  
                             

                                                     
                                <a class="btn btn-info btn-icon" href="{{ route('editorial.edit',$editoriales->id) }}">   <span class="icon icon-edit"></span>
                     			      <span class="caption">edit</span>
                     			    </a>
                            </td>

                        </tr>
                        @endforeach
                    </tbody>
                  
                  </table>
                </div>
              </div>
            </div>
          </div>



@endsection